export type NavItem = {
  title: string;
  href: string;
};

export type NavSection = {
  title: string;
  slug: string;
  items: NavItem[];
};

export const navigation: NavSection[] = [
  {
    title: "Getting Started",
    slug: "getting-started",
    items: [
      { title: "Introduction", href: "/docs/getting-started" },
      { title: "How to use this site", href: "/docs/getting-started#how-to-use-this-site" },
    ],
  },
  {
    title: "React + TypeScript",
    slug: "react",
    items: [
      { title: "Function components with typed props", href: "/docs/react#function-components-with-typed-props" },
      { title: "Children typing", href: "/docs/react#children-typing" },
      { title: "Event handlers", href: "/docs/react#event-handlers" },
      { title: "useState with types", href: "/docs/react#usestate-with-types" },
      { title: "useState with objects", href: "/docs/react#usestate-with-objects-complex-state" },
      { title: "useEffect", href: "/docs/react#useeffect" },
      { title: "Derived state", href: "/docs/react#derived-state-dont-useeffect-this" },
      { title: "Refs", href: "/docs/react#refs" },
      { title: "useMemo and useCallback", href: "/docs/react#usememo-and-usecallback" },
      { title: "Conditional rendering", href: "/docs/react#conditional-rendering" },
      { title: "Lists with keys", href: "/docs/react#lists-with-keys" },
      { title: "Lifting state up", href: "/docs/react#lifting-state-up" },
      { title: "Custom hooks", href: "/docs/react#custom-hooks" },
      { title: "Context", href: "/docs/react#context-when-and-when-not" },
      { title: "Zustand", href: "/docs/react#zustand-when-context-isnt-enough" },
      { title: "Forms with react-hook-form + Zod", href: "/docs/react#forms-with-react-hook-form--zod" },
      { title: "Common utility types", href: "/docs/react#common-utility-types" },
      { title: "as prop / polymorphic components", href: "/docs/react#as-prop--polymorphic-components" },
    ],
  },
  {
    title: "Tailwind",
    slug: "tailwind",
    items: [
      { title: "Spacing scale", href: "/docs/tailwind#spacing-scale-the-one-thing-to-memorize" },
      { title: "Flexbox basics", href: "/docs/tailwind#flexbox-basics" },
      { title: "Centering everything", href: "/docs/tailwind#centering-everything" },
      { title: "Justify and align", href: "/docs/tailwind#justify-and-align" },
      { title: "Flex-1", href: "/docs/tailwind#flex-1-the-take-up-the-rest-trick" },
      { title: "Flex direction", href: "/docs/tailwind#flex-direction" },
      { title: "Flex wrap", href: "/docs/tailwind#flex-wrap" },
      { title: "Grid basics", href: "/docs/tailwind#grid-basics" },
      { title: "Grid with column spans", href: "/docs/tailwind#grid-with-column-spans" },
      { title: "Responsive grid", href: "/docs/tailwind#responsive-grid-the-dashboard-pattern" },
      { title: "auto-fit / minmax", href: "/docs/tailwind#auto-fit--minmax-responsive-without-breakpoints" },
      { title: "Sidebar layout", href: "/docs/tailwind#sidebar-layout-the-classic" },
      { title: "Sticky header", href: "/docs/tailwind#sticky-header" },
      { title: "Responsive prefixes", href: "/docs/tailwind#responsive-prefixes" },
      { title: "Dark mode", href: "/docs/tailwind#dark-mode" },
      { title: "Hover, focus, active", href: "/docs/tailwind#hover-focus-active" },
      { title: "Group hover", href: "/docs/tailwind#group-hover" },
      { title: "Peer state", href: "/docs/tailwind#peer-state-sibling-driven-styling" },
      { title: "cn() helper", href: "/docs/tailwind#conditional-classes-with-cn" },
      { title: "cva for variants", href: "/docs/tailwind#cva-for-variants" },
      { title: "Container + max-width", href: "/docs/tailwind#container--max-width-pattern" },
      { title: "Aspect ratio", href: "/docs/tailwind#aspect-ratio" },
      { title: "Truncate text", href: "/docs/tailwind#truncate-text" },
      { title: "Arbitrary values", href: "/docs/tailwind#arbitrary-values" },
    ],
  },
  {
    title: "Next.js",
    slug: "nextjs",
    items: [
      { title: "Server vs Client Components", href: "/docs/nextjs#server-vs-client-components" },
      { title: "File structure", href: "/docs/nextjs#file-structure-the-convention-i-follow" },
      { title: "Routes", href: "/docs/nextjs#routes" },
      { title: "Dynamic routes", href: "/docs/nextjs#dynamic-routes" },
      { title: "Special files", href: "/docs/nextjs#special-files" },
      { title: "Layouts", href: "/docs/nextjs#layouts" },
      { title: "Loading states", href: "/docs/nextjs#loading-states" },
      { title: "Error boundaries", href: "/docs/nextjs#error-boundaries" },
      { title: "Linking", href: "/docs/nextjs#linking" },
      { title: "Programmatic navigation", href: "/docs/nextjs#programmatic-navigation" },
      { title: "Reading the URL", href: "/docs/nextjs#reading-the-url" },
      { title: "Server Actions", href: "/docs/nextjs#server-actions" },
      { title: "Server Actions from a client component", href: "/docs/nextjs#server-actions-from-a-client-component" },
      { title: "Route Handlers", href: "/docs/nextjs#route-handlers-when-you-need-an-actual-api" },
      { title: "Caching and revalidation", href: "/docs/nextjs#caching-and-revalidation" },
      { title: "Middleware", href: "/docs/nextjs#middleware" },
      { title: "Metadata (SEO)", href: "/docs/nextjs#metadata-seo" },
      { title: "Images", href: "/docs/nextjs#images" },
      { title: "Fonts", href: "/docs/nextjs#fonts" },
      { title: "Environment variables", href: "/docs/nextjs#environment-variables" },
      { title: "Data Access Layer", href: "/docs/nextjs#data-access-layer-dal-pattern" },
      { title: "Parallel routes", href: "/docs/nextjs#parallel-routes-modals-side-panels" },
      { title: "Best practices recap", href: "/docs/nextjs#best-practices-recap" },
    ],
  },
  {
    title: "TanStack Start",
    slug: "tanstack-start",
    items: [
      { title: "Setup", href: "/docs/tanstack-start#setup" },
      { title: "File-based routing", href: "/docs/tanstack-start#file-based-routing" },
      { title: "Defining a route", href: "/docs/tanstack-start#defining-a-route" },
      { title: "Server functions", href: "/docs/tanstack-start#server-functions" },
      { title: "Type-safe links", href: "/docs/tanstack-start#type-safe-links" },
      { title: "Loaders + caching", href: "/docs/tanstack-start#loaders--caching" },
      { title: "When to pick TanStack Start over Next.js", href: "/docs/tanstack-start#when-to-pick-tanstack-start-over-nextjs" },
    ],
  },
  {
    title: "Drizzle + Postgres",
    slug: "drizzle",
    items: [
      { title: "Setup", href: "/docs/drizzle#setup" },
      { title: "Client (Neon serverless)", href: "/docs/drizzle#client-neon-serverless-for-cloudflarevercel" },
      { title: "Client (node-postgres)", href: "/docs/drizzle#client-node-postgres-for-traditional-node-deployments" },
      { title: "Schema", href: "/docs/drizzle#schema" },
      { title: "Migrations", href: "/docs/drizzle#migrations" },
      { title: "CRUD — Read", href: "/docs/drizzle#crud--read" },
      { title: "CRUD — Create", href: "/docs/drizzle#crud--create" },
      { title: "CRUD — Update", href: "/docs/drizzle#crud--update" },
      { title: "CRUD — Delete", href: "/docs/drizzle#crud--delete" },
      { title: "Joins", href: "/docs/drizzle#joins-manual-style" },
      { title: "Transactions", href: "/docs/drizzle#transactions" },
      { title: "Pagination", href: "/docs/drizzle#pagination" },
      { title: "Common operators", href: "/docs/drizzle#common-operators-cheatsheet" },
    ],
  },
  {
    title: "APIs",
    slug: "apis",
    items: [
      { title: "fetch (the basics)", href: "/docs/apis#fetch-the-basics" },
      { title: "POST with JSON", href: "/docs/apis#post-with-json" },
      { title: "With auth header", href: "/docs/apis#with-auth-header" },
      { title: "Type-safe fetch wrapper", href: "/docs/apis#type-safe-fetch-wrapper" },
      { title: "Zod validation", href: "/docs/apis#zod-validation-request-bodies" },
      { title: "Zod patterns", href: "/docs/apis#zod-patterns" },
      { title: "Error handling pattern", href: "/docs/apis#error-handling-pattern" },
      { title: "Server Actions with validation", href: "/docs/apis#server-actions-with-validation" },
      { title: "TanStack Query", href: "/docs/apis#tanstack-query-server-state-on-the-client" },
    ],
  },
  {
    title: "Auth (Better Auth)",
    slug: "auth",
    items: [
      { title: "Setup", href: "/docs/auth#setup" },
      { title: "Generate auth tables", href: "/docs/auth#generate-auth-tables" },
      { title: "Mount the route handler", href: "/docs/auth#mount-the-route-handler" },
      { title: "Client setup", href: "/docs/auth#client-setup" },
      { title: "Sign in / sign up", href: "/docs/auth#sign-in--sign-up" },
      { title: "Get session in server components", href: "/docs/auth#get-session-in-server-components" },
      { title: "Get session in client components", href: "/docs/auth#get-session-in-client-components" },
      { title: "Protect a route via middleware", href: "/docs/auth#protect-a-route-via-middleware" },
      { title: "Sign out", href: "/docs/auth#sign-out" },
      { title: "Role-based access", href: "/docs/auth#role-based-access-manual" },
    ],
  },
  {
    title: "AI Integration",
    slug: "ai",
    items: [
      { title: "Vercel AI SDK", href: "/docs/ai#vercel-ai-sdk-the-easy-default" },
      { title: "Simple text generation", href: "/docs/ai#pattern-simple-text-generation" },
      { title: "Streaming chat", href: "/docs/ai#pattern-streaming-chat-the-most-common-ui" },
      { title: "Structured output", href: "/docs/ai#pattern-structured-output-json-with-a-schema" },
      { title: "Tool calling", href: "/docs/ai#pattern-tool-calling-let-the-model-use-functions" },
      { title: "RAG", href: "/docs/ai#pattern-rag-retrieval-augmented-generation" },
      { title: "Agents", href: "/docs/ai#pattern-agents" },
      { title: "LangChain", href: "/docs/ai#langchain-when-you-need-orchestration" },
      { title: "Hugging Face", href: "/docs/ai#hugging-face-open-source-models-embeddings" },
      { title: "Provider quick-pick", href: "/docs/ai#provider-quick-pick" },
      { title: "Streaming structured output", href: "/docs/ai#streaming-structured-output" },
      { title: "Cost / rate limit tips", href: "/docs/ai#cost--rate-limit-tips" },
    ],
  },
  {
    title: "Patterns",
    slug: "patterns",
    items: [
      { title: "cn() helper", href: "/docs/patterns#cn-for-conditional-tailwind-classes" },
      { title: "Optimistic UI", href: "/docs/patterns#optimistic-ui" },
      { title: "Debouncing", href: "/docs/patterns#debouncing-search-inputs" },
      { title: "Throttling", href: "/docs/patterns#throttling" },
      { title: "Loading states", href: "/docs/patterns#loading-states-the-three-you-always-need" },
      { title: "Empty states", href: "/docs/patterns#empty-states-matter" },
      { title: "Toast notifications", href: "/docs/patterns#toast-notifications" },
      { title: "Modals", href: "/docs/patterns#modals-shadcn-dialog" },
      { title: "Confirmation dialog", href: "/docs/patterns#confirmation-dialog" },
      { title: "Copy to clipboard", href: "/docs/patterns#copy-to-clipboard" },
      { title: "Format dates", href: "/docs/patterns#format-dates-date-fns" },
      { title: "Image upload", href: "/docs/patterns#image-upload" },
      { title: "Pagination URL state", href: "/docs/patterns#pagination-url-state" },
      { title: "Skeleton loaders", href: "/docs/patterns#skeleton-loaders-better-than-spinners-for-content" },
      { title: "Infinite scroll", href: "/docs/patterns#infinite-scroll-intersection-observer" },
      { title: "Local storage hook", href: "/docs/patterns#local-storage-hook" },
      { title: "Keyboard shortcuts", href: "/docs/patterns#keyboard-shortcuts" },
      { title: "Prevent layout shift", href: "/docs/patterns#prevent-layout-shift-cls" },
      { title: "Env variable validation", href: "/docs/patterns#env-variable-validation-with-zod" },
    ],
  },
  {
    title: "Resources",
    slug: "resources",
    items: [
      { title: "Frameworks & runtimes", href: "/docs/resources#frameworks--runtimes" },
      { title: "Styling & UI", href: "/docs/resources#styling--ui" },
      { title: "Forms & validation", href: "/docs/resources#forms--validation" },
      { title: "State management", href: "/docs/resources#state-management" },
      { title: "Data fetching & caching", href: "/docs/resources#data-fetching--caching" },
      { title: "Database & ORM", href: "/docs/resources#database--orm" },
      { title: "Auth", href: "/docs/resources#auth" },
      { title: "AI & LLMs", href: "/docs/resources#ai--llms" },
      { title: "Date & time", href: "/docs/resources#date--time" },
      { title: "File uploads & storage", href: "/docs/resources#file-uploads--storage" },
      { title: "Email", href: "/docs/resources#email" },
      { title: "Payments", href: "/docs/resources#payments" },
      { title: "Background jobs & queues", href: "/docs/resources#background-jobs--queues" },
      { title: "Realtime", href: "/docs/resources#realtime" },
      { title: "Hosting & deployment", href: "/docs/resources#hosting--deployment" },
      { title: "Analytics & monitoring", href: "/docs/resources#analytics--monitoring" },
      { title: "Testing", href: "/docs/resources#testing" },
      { title: "DX & tooling", href: "/docs/resources#dx--tooling" },
      { title: "Workflow & automation", href: "/docs/resources#workflow--automation" },
      { title: "Documentation & learning", href: "/docs/resources#documentation--learning" },
      { title: "Cheatsheet hubs", href: "/docs/resources#cheatsheet-hubs" },
      { title: "Inspiration / templates", href: "/docs/resources#inspiration--templates" },
    ],
  },
];

export const flatNavSlugs = navigation.map((s) => s.slug);

export function findSection(slug: string) {
  return navigation.find((s) => s.slug === slug);
}

export function getAdjacent(slug: string) {
  const i = navigation.findIndex((s) => s.slug === slug);
  return {
    prev: i > 0 ? navigation[i - 1] : null,
    next: i < navigation.length - 1 ? navigation[i + 1] : null,
  };
}
